### ISSUE TITLE
Review ticket week 3

### ISSUE THREAD

**Issue by Unlqsting** [Unlqsting/blog#2]
Here is the link for my AppLab game: https://studio.code.org/projects/applab/wRy7RcsYiP9vkEcxZ060wxs4Anr52Mdyjh_-OY9OaY4

Here is the link for the blog to the applab quiz and plans for the college board create task: https://unlqsting.github.io/AP-Comp-fastpages/developer%20tools/applab/planning/2022/09/08/AppLabquiz.html

**Comment by A1234l** [comment]
The quiz was very well made. There was not only multiple choice, but there was also selecting multiple answers as well as an frq response question. The timeout idea used in the quiz was very creative. The blog was well made and reflected on all aspects required. The college board project was also a very good idea. This is a good candidate for a 2.7+ score.
